// GENERATED by a one-off fixture script: do not hand-edit.
//
// A real ECDSA P-256 chain and real signatures, minted with openssl, standing in
// for Fulcio's. Committed so `signature.test.ts` is hermetic: a test that
// generated its own keys at run time could pass for the wrong reason if key
// generation drifted.
//
// The leaf's SAN and OIDC-issuer extension carry the pinned release identity, so
// these bytes exercise the real accept path rather than a relaxed one.

export const TEST_ROOT_PEM =
  "-----BEGIN CERTIFICATE-----\nMIIBizCCATGgAwIBAgIUSWzKg2wDl3JchwQTaP+suKN1xGswCgYIKoZIzj0EAwIw\nGzEZMBcGA1UEAwwQVGVzdCBGdWxjaW8gUm9vdDAeFw0yNjA4MjUxNjA5MzVaFw0z\nNjA4MjIxNjA5MzVaMBsxGTAXBgNVBAMMEFRlc3QgRnVsY2lvIFJvb3QwWTATBgcq\nhkjOPQIBBggqhkjOPQMBBwNCAATaJsM9QklRmMOrcyToRDz2+C6VN3v0TqbwcNVt\nMQnnIVWpGmcf39QUoh70vmSrJtYkEuAv0vEr2vcmLCPYr+GJo1MwUTAdBgNVHQ4E\nFgQUhu4kOfFx30pr3WztrusZTHxsYA0wHwYDVR0jBBgwFoAUhu4kOfFx30pr3Wzt\nrusZTHxsYA0wDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNIADBFAiAeqHpJ\nMqW9PfDvJIMbAdD+X16dRPtB/tAy0sdDyU+CiQIhAL7UuZTPmtxWTFKl9fg3sZ/n\n27ButJBZsC3Ur4OXr1nB\n-----END CERTIFICATE-----\n";

export const ROGUE_ROOT_PEM =
  "-----BEGIN CERTIFICATE-----\nMIIBfjCCASWgAwIBAgIUeIHamw6tvS/pGoZF7frvftnrqv4wCgYIKoZIzj0EAwIw\nFTETMBEGA1UEAwwKUm9ndWUgUm9vdDAeFw0yNjA4MjUxNjA5MzVaFw0zNjA4MjIx\nNjA5MzVaMBUxEzARBgNVBAMMClJvZ3VlIFJvb3QwWTATBgcqhkjOPQIBBggqhkjO\nPQMBBwNCAATFFttpLdViyr7nbaBMBPINjYnXVBB6HpHuKXL7RwOHYYqI3GeCu/0A\nXhdQl4HaS5a55iSJmae0gkchqgZU7czmo1MwUTAdBgNVHQ4EFgQUlKCD3yktxmrc\nXHYpsF0jtJzmd+8wHwYDVR0jBBgwFoAUlKCD3yktxmrcXHYpsF0jtJzmd+8wDwYD\nVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNHADBEAiBDlqA7VU81WmzQTlEo+p6h\nZcF00NTMjYjwqwMCxIwREQIgQCOrOUcrfTCotlJOZqlmMF6HVvCY8mSiEGQvSjUa\nRCc=\n-----END CERTIFICATE-----\n";

export const PAYLOAD =
  "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa  wego-darwin-arm64\n";

const LEAF_DER =
  "MIICCzCCAbCgAwIBAgIUJYAtyEOp2Mkk9SllFhR7C93E2jMwCgYIKoZIzj0EAwIwGzEZMBcGA1UEAwwQVGVzdCBGdWxjaW8gUm9vdDAeFw0yNjA4MjUxNjA5MzVaFw0zNjA4MjIxNjA5MzVaMAAwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQhHd0hxm0bizQggKMTbIm4dmcNDd+kDzBPwwaLeJ+ziKHKVyUxQqEEzOBuQ2J0HEs+8z6Ty4RRiwuAhjLgNts9o4HsMIHpMFwGA1UdEQRVMFOGUWh0dHBzOi8vZ2l0aHViLmNvbS93ZWdvL3dlZ28tYWkvLmdpdGh1Yi93b3JrZmxvd3MvcmVsZWFzZS1jbGkueW1sQHJlZnMvaGVhZHMvbWFpbjA7BgorBgEEAYO/MAEIBC0MK2h0dHBzOi8vdG9rZW4uYWN0aW9ucy5naXRodWJ1c2VyY29udGVudC5jb20wDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUh2uik/uYyEWz6muyr2yoUAues2IwHwYDVR0jBBgwFoAUhu4kOfFx30pr3WztrusZTHxsYA0wCgYIKoZIzj0EAwIDSQAwRgIhAKb85a0d3MtC0v7K2UCIsV9liXBJ8tx7HuuFqBn1wMXyAiEAlZaj1lZuDU1ioS2K1DjNlWHJQvDTPuPPKiSG/vxYJAg=";
const ROGUE_LEAF_DER =
  "MIICBDCCAaqgAwIBAgIUciZVWE1YBNxrOSuwi0Enj5vPQCEwCgYIKoZIzj0EAwIwFTETMBEGA1UEAwwKUm9ndWUgUm9vdDAeFw0yNjA4MjUxNjA5MzVaFw0zNjA4MjIxNjA5MzVaMAAwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQhHd0hxm0bizQggKMTbIm4dmcNDd+kDzBPwwaLeJ+ziKHKVyUxQqEEzOBuQ2J0HEs+8z6Ty4RRiwuAhjLgNts9o4HsMIHpMFwGA1UdEQRVMFOGUWh0dHBzOi8vZ2l0aHViLmNvbS93ZWdvL3dlZ28tYWkvLmdpdGh1Yi93b3JrZmxvd3MvcmVsZWFzZS1jbGkueW1sQHJlZnMvaGVhZHMvbWFpbjA7BgorBgEEAYO/MAEIBC0MK2h0dHBzOi8vdG9rZW4uYWN0aW9ucy5naXRodWJ1c2VyY29udGVudC5jb20wDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUh2uik/uYyEWz6muyr2yoUAues2IwHwYDVR0jBBgwFoAUlKCD3yktxmrcXHYpsF0jtJzmd+8wCgYIKoZIzj0EAwIDSAAwRQIhAPcGjp0xT7UjsgotimABPKPH9ataHRhElfuUbgwudFcSAiBKBY58yrjfNYaQADmJQzfOPKi17B5LxE5SJFJ97dlfXQ==";
const OTHER_IDENTITY_LEAF_DER =
  "MIICBzCCAa2gAwIBAgIUDn3GzQiAXRdhMOk1mlyBv60JbLYwCgYIKoZIzj0EAwIwGzEZMBcGA1UEAwwQVGVzdCBGdWxjaW8gUm9vdDAeFw0yNjA4MjUxNjA5MzVaFw0zNjA4MjIxNjA5MzVaMAAwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQhHd0hxm0bizQggKMTbIm4dmcNDd+kDzBPwwaLeJ+ziKHKVyUxQqEEzOBuQ2J0HEs+8z6Ty4RRiwuAhjLgNts9o4HpMIHmMFkGA1UdEQRSMFCGTmh0dHBzOi8vZ2l0aHViLmNvbS93ZWdvL3dlZ28tYWkvLmdpdGh1Yi93b3JrZmxvd3MvZWRnZS1jbGkueW1sQHJlZnMvaGVhZHMvbWFpbjA7BgorBgEEAYO/MAEIBC0MK2h0dHBzOi8vdG9rZW4uYWN0aW9ucy5naXRodWJ1c2VyY29udGVudC5jb20wDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUh2uik/uYyEWz6muyr2yoUAues2IwHwYDVR0jBBgwFoAUhu4kOfFx30pr3WztrusZTHxsYA0wCgYIKoZIzj0EAwIDSAAwRQIhAI3WZePDZVyB7GaYOf484AoMqSCyH6QQTPX+UrgqAqLkAiBENGYZLNDE5793IHSHT15hk6sx2/OL/LTSKFM9QOlQvQ==";
const SIGNATURE =
  "MEYCIQCuz4hTSwVjbhmidBk1qJbuVZhz7+n3OLfFLqOvfB+fywIhAJNQtXpOg0rGoFo8A9iseq/5o9jYAy4M+JHv416Yd8pX";
const WRONG_PAYLOAD_SIGNATURE =
  "MEUCIEWF7KrCWIwgwXhteK3QY1/uCzofQiBgYtat7y2KabHrAiEA6cXFMTf5H4um4fXdQhH8qUrQ2VUDMtIy0iSkYsjM4s8=";
export const INTEGRATED_TIME = 1787674205;

export const PAYLOAD_DIGEST_B64 =
  "LQfZDViNLJPsQFRWCjt06jC4100BtcTS/bDZGSdi+ak=";

interface BundleOverrides {
  certDer?: string;
  signature?: string;
  digest?: string | null;
  integratedTime?: number | null;
}

/** A Sigstore v0.3 bundle over PAYLOAD, with any part swappable for a negative case. */
export function bundle(overrides: BundleOverrides = {}): unknown {
  const digest =
    overrides.digest === undefined ? PAYLOAD_DIGEST_B64 : overrides.digest;
  const time =
    overrides.integratedTime === undefined
      ? INTEGRATED_TIME
      : overrides.integratedTime;
  return {
    mediaType: "application/vnd.dev.sigstore.bundle.v0.3+json",
    verificationMaterial: {
      certificate: { rawBytes: overrides.certDer ?? LEAF_DER },
      ...(time === null
        ? {}
        : { tlogEntries: [{ integratedTime: String(time) }] }),
    },
    messageSignature: {
      ...(digest === null
        ? {}
        : { messageDigest: { algorithm: "SHA2_256", digest } }),
      signature: overrides.signature ?? SIGNATURE,
    },
  };
}

/** A record whose certificate came from a root we do not pin. */
export const ROGUE_ROOT_CERT_DER = ROGUE_LEAF_DER;
/** A record signed for a different workflow in the same repo. */
export const OTHER_IDENTITY_CERT_DER = OTHER_IDENTITY_LEAF_DER;
/** A signature made over different bytes entirely. */
export const SIGNATURE_OVER_OTHER_BYTES = WRONG_PAYLOAD_SIGNATURE;

/**
 * The test leaf's private key, so a suite can sign an arbitrary manifest and get a
 * record the real verifier accepts.
 *
 * Safe to commit: it is a throwaway key under a throwaway root that only
 * `TEST_ROOT_PEM` trusts. The binary pins Fulcio's real roots
 * (`sigstore-roots.ts`), so a record signed with this key is refused everywhere
 * outside a test that pins the test root.
 *
 * It keeps `update.test.ts` running the real verifier; a stubbed verification
 * would let the fail-closed behaviour rot without a test going red.
 */
const TEST_SIGNING_KEY_PKCS8 =
  "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgV6rI/dk6Mbmqs6NfcV9pr4g2KcehjPsJtkOxx8Jx/+uhRANCAAQhHd0hxm0bizQggKMTbIm4dmcNDd+kDzBPwwaLeJ+ziKHKVyUxQqEEzOBuQ2J0HEs+8z6Ty4RRiwuAhjLgNts9";

const TEST_LEAF_DER =
  "MIICCzCCAbCgAwIBAgIUJYAtyEOp2Mkk9SllFhR7C93E2jMwCgYIKoZIzj0EAwIwGzEZMBcGA1UEAwwQVGVzdCBGdWxjaW8gUm9vdDAeFw0yNjA4MjUxNjA5MzVaFw0zNjA4MjIxNjA5MzVaMAAwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQhHd0hxm0bizQggKMTbIm4dmcNDd+kDzBPwwaLeJ+ziKHKVyUxQqEEzOBuQ2J0HEs+8z6Ty4RRiwuAhjLgNts9o4HsMIHpMFwGA1UdEQRVMFOGUWh0dHBzOi8vZ2l0aHViLmNvbS93ZWdvL3dlZ28tYWkvLmdpdGh1Yi93b3JrZmxvd3MvcmVsZWFzZS1jbGkueW1sQHJlZnMvaGVhZHMvbWFpbjA7BgorBgEEAYO/MAEIBC0MK2h0dHBzOi8vdG9rZW4uYWN0aW9ucy5naXRodWJ1c2VyY29udGVudC5jb20wDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUh2uik/uYyEWz6muyr2yoUAues2IwHwYDVR0jBBgwFoAUhu4kOfFx30pr3WztrusZTHxsYA0wCgYIKoZIzj0EAwIDSQAwRgIhAKb85a0d3MtC0v7K2UCIsV9liXBJ8tx7HuuFqBn1wMXyAiEAlZaj1lZuDU1ioS2K1DjNlWHJQvDTPuPPKiSG/vxYJAg=";

/** Signs `manifest` as the release workflow would and returns the Sigstore bundle. */
export async function signManifest(
  manifest: string | Uint8Array,
): Promise<unknown> {
  const bytes = (
    typeof manifest === "string" ? new TextEncoder().encode(manifest) : manifest
  ) as Uint8Array<ArrayBuffer>;
  const key = await crypto.subtle.importKey(
    "pkcs8",
    Uint8Array.from(
      atob(TEST_SIGNING_KEY_PKCS8),
      (ch) => ch.codePointAt(0) ?? 0,
    ),
    { name: "ECDSA", namedCurve: "P-256" },
    false,
    ["sign"],
  );
  // WebCrypto signs to raw r|s; cosign records the DER encoding, so re-encode.
  const raw = new Uint8Array(
    await crypto.subtle.sign({ name: "ECDSA", hash: "SHA-256" }, key, bytes),
  );
  const der = rawEcdsaToDer(raw);
  const digest = new Uint8Array(await crypto.subtle.digest("SHA-256", bytes));
  return {
    mediaType: "application/vnd.dev.sigstore.bundle.v0.3+json",
    verificationMaterial: {
      certificate: { rawBytes: TEST_LEAF_DER },
      tlogEntries: [{ integratedTime: String(INTEGRATED_TIME) }],
    },
    messageSignature: {
      messageDigest: { algorithm: "SHA2_256", digest: toBase64(digest) },
      signature: toBase64(der),
    },
  };
}

function toBase64(bytes: Uint8Array): string {
  let out = "";
  for (const byte of bytes) out += String.fromCodePoint(byte);
  return btoa(out);
}

/** raw r|s (32+32) -> `SEQUENCE { INTEGER r, INTEGER s }`. */
function rawEcdsaToDer(raw: Uint8Array): Uint8Array {
  const half = raw.length / 2;
  const ints: number[][] = [];
  for (const part of [raw.subarray(0, half), raw.subarray(half)]) {
    let i = 0;
    while (i < part.length - 1 && part[i] === 0) i++;
    const body = Array.from(part.subarray(i));
    // DER INTEGERs are signed, so a leading high bit needs a zero pad.
    if (body[0] >= 0x80) body.unshift(0);
    ints.push([0x02, body.length, ...body]);
  }
  const content = [...ints[0], ...ints[1]];
  return new Uint8Array([0x30, content.length, ...content]);
}
