#!/usr/bin/env bun
import { fileURLToPath } from "node:url";

/**
 * Refresh the vendored API contract at `contract/openapi.json`.
 *
 * The CLI is a separate repository from the API, so there is no path it can
 * read the contract from at build time. It vendors one instead: this script
 * fetches the published document, writes it here, and the rest of the chain
 * (`api-types:generate`, Checks A and C, Check B) runs against the committed
 * copy. Refreshing is a deliberate act - run this, commit the JSON diff on its
 * own, then fix whatever the checks report.
 *
 * `bun run api-contract:refresh` chains `api-types:generate` after this script,
 * because the types on disk were generated by `postinstall` from the PREVIOUS
 * contract. A refresh that stopped here would leave them behind, and the next
 * `bun run typecheck` would compare the CLI against shapes the API no longer
 * publishes - which is the stale-snapshot failure this file exists to end.
 *
 * The written file is formatted by biome, the same formatter every other file
 * in this repository goes through, so `contract/` needs no exemption and a
 * refresh never leaves `bun run lint` red.
 *
 * Always production. The document carries a `servers` block naming the host it
 * was served from, so a staging or preview URL would rewrite that line on every
 * refresh and make the diff unreadable, on top of vendoring a contract nothing
 * ships against.
 */

/** The published contract. Production, unauthenticated, never staging. */
const CONTRACT_URL = "https://api.wego.com/openapi";

const OUTPUT = new URL("../contract/openapi.json", import.meta.url);

/** Attempts in total, not retries after the first: the API is behind a CDN and
 *  a single 5xx or dropped connection is not worth a failed refresh. */
const ATTEMPTS = 4;

/** Between attempts. Short: this is a person waiting at a terminal. */
const RETRY_DELAY_MS = 1_000;

/** A whole-request deadline per attempt. `fetch` has none of its own, so a
 *  connection that opens and then stalls hangs the refresh forever - and never
 *  reaches the retry below, which is the one thing that would have saved it.
 *  15s is generous for a ~200KB document and still bounded; the CI drift step
 *  bounds its own fetch the same way with `curl --max-time 20`. */
const FETCH_TIMEOUT_MS = 15_000;

/** The minimum shape that makes a body a contract rather than an error page.
 *  A 200 carrying HTML from a misrouted edge would otherwise be committed. */
export interface ContractDocument {
  openapi: string;
  info: { version: string };
  paths: Record<string, unknown>;
}

/** Why this body is not a contract, or `undefined` when it is one. */
export function contractProblem(body: unknown): string | undefined {
  if (typeof body !== "object" || body === null || Array.isArray(body)) {
    return "the body is not a JSON object";
  }
  const document = body as Partial<ContractDocument>;
  if (typeof document.openapi !== "string") {
    return "the body has no `openapi` version string";
  }
  if (typeof document.info?.version !== "string") {
    return "the body has no `info.version` string";
  }
  if (
    typeof document.paths !== "object" ||
    document.paths === null ||
    Array.isArray(document.paths)
  ) {
    return "the body has no `paths` object";
  }
  return undefined;
}

/** A first pass at the file: valid JSON, two-space indent, trailing newline.
 *  Biome then owns the final shape - see `formatContract`. This exists so the
 *  file on disk is already sane if the format step is what fails. */
export function serializeContract(document: ContractDocument): string {
  return `${JSON.stringify(document, null, 2)}\n`;
}

/**
 * Hand the written file to biome, the repository's one formatter.
 *
 * The contract is committed, so it is subject to `bun run lint` like every
 * other file. Formatting it here rather than exempting `contract/` is what
 * keeps a refresh from leaving the tree lint-red until someone remembers
 * `bun run format`, and it means nobody has to know that this one file is
 * special. Biome's output is deterministic, so a refresh that fetches an
 * unchanged document produces no diff.
 *
 * Throws on failure: a contract that lint would reject must not be committed.
 */
function formatContract(): void {
  const formatted = Bun.spawnSync(
    ["bunx", "biome", "format", "--write", "contract/openapi.json"],
    {
      cwd: fileURLToPath(new URL("..", import.meta.url)),
      stdout: "pipe",
      stderr: "pipe",
    },
  );
  if (formatted.exitCode !== 0) {
    throw new Error(
      `biome could not format contract/openapi.json: ${formatted.stderr.toString().trim()}`,
    );
  }
}

async function fetchContract(): Promise<ContractDocument> {
  let lastFailure = "";
  for (let attempt = 1; attempt <= ATTEMPTS; attempt++) {
    try {
      const response = await fetch(CONTRACT_URL, {
        headers: { accept: "application/json" },
        signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
      });
      if (!response.ok) {
        lastFailure = `HTTP ${response.status} ${response.statusText}`;
      } else {
        const body: unknown = await response.json();
        const problem = contractProblem(body);
        if (problem) {
          lastFailure = problem;
        } else {
          return body as ContractDocument;
        }
      }
    } catch (error) {
      lastFailure = error instanceof Error ? error.message : String(error);
    }
    if (attempt < ATTEMPTS) {
      console.error(
        `attempt ${attempt}/${ATTEMPTS} failed (${lastFailure}), retrying`,
      );
      await Bun.sleep(RETRY_DELAY_MS);
    }
  }
  throw new Error(`could not fetch ${CONTRACT_URL}: ${lastFailure}`);
}

/** The version in the file on disk, or `undefined` on a first fetch. */
async function committedVersion(): Promise<string | undefined> {
  const file = Bun.file(OUTPUT);
  if (!(await file.exists())) return undefined;
  try {
    const document: unknown = await file.json();
    const version = (document as Partial<ContractDocument>)?.info?.version;
    return typeof version === "string" ? version : undefined;
  } catch {
    return undefined;
  }
}

if (import.meta.main) {
  const before = await committedVersion();
  const document = await fetchContract();
  await Bun.write(OUTPUT, serializeContract(document));
  formatContract();
  console.log(`contract/openapi.json <- ${CONTRACT_URL}`);
  console.log(`  was: ${before ?? "(no committed contract)"}`);
  console.log(`  now: ${document.info.version}`);
  if (before === document.info.version) {
    console.log("  no version change; the body may still differ");
  }
}
